# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

"on":
  push:
    branches:
      - dev
      - test
      - stage
    tags: ["v*.*.*"]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@nicdub-multi-repo
    secrets:
      gitops_token: ${{ secrets.CD_TOKEN }}
      registry_token: ${{ secrets.GITHUB_TOKEN }}
      registry_token2: ${{ secrets.QUAY_TOKEN }}
    with:
      org: epfl-enac
      repo: enack8s-cd-tester
      build_context: '[ "./test"]' #', "./backend" ]' # context paths to build
      # registry:
      registry_path: epfl-enac/enack8s-cd-tester
      # registry_username:
      registry2: quay-its.epfl.ch
      registry_path2: svc1751
      registry_username2: svc1751+ghaction

      # registries: |
      #   [
      #     {
      #       "registry": "ghcr.io",
      #       "argo_repositories": ["EPFL-ENAC/enack8s-app-config"]
      #     },
      #     {
      #       "registry": "quay-its.epfl.ch",
      #       "registry_path": "svc1751",
      #       "registry_username": "svc1751+ghaction",
      #       "argo_repositories": ["EPFL-ENAC/openshift-app-config"]
      #     }
      #   ]
