# https://github.com/EPFL-ENAC/epfl-enac-build-push-deploy-action#readme
name: deploy

"on":
  push:
    branches:
      - dev
      - test
      - stage
    tags: ["v*.*.*"]

jobs:
  deploy:
    permissions:
      contents: read
      packages: write
    uses: EPFL-ENAC/epfl-enac-build-push-deploy-action/.github/workflows/deploy.yml@feat/15-scan-vulnerabilities
    secrets:
      token: ${{ secrets.CD_TOKEN }}
    with:
      org: epfl-enac
      repo: enack8s-cd-tester
      build_context: '[ "./frontend", "./backend" ]' # context paths to build
      # argo_repository: "['EPFL-ENAC/enack8s-app-config', 'EPFL-ENAC/openshift-app-config']"
      # skip_vulnerability_scan: true
